apiVersion: v1
kind: Secret
metadata:
  name: nblaunch-secrets
type: Opaque
stringData:
  JUPYTERHUB_API_TOKEN: "REPLACE_ME_WITH_RANDOM_TOKEN"

  SECRET: "REPLACE_ME_WITH_RANDOM_HMAC_SECRET"

  NBGALLERY_SERVICE_TOKEN: "REPLACE_ME_WITH_NBGALLERY_SERVICE_TOKEN"

  COOKIE_SECRET: "REPLACE_ME_WITH_RANDOM_COOKIE_SECRET"
